version: 2.0.0-SNAPSHOT

# Spring Boot Configuration
spring:
  main:
    web-application-type: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Google API Configuration
google:
  login:
    timeout: 120
    port: 8080
    enable: true
  api:
    throttle: 5

# Export Configuration
export:
  source:
    jahresplan:
      esg: "JP.xlsm"
      be: "%new"
      zh: "%new"
      fullday: "%new"