version: 2.0.0

# Spring Boot Configuration
spring:
  main:
    web-application-type: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Google API Configuration
google:
  login:
    timeout: 120
    port: 8080
    enable: true
  api:
    throttle: 5

calendar:
  planning-suffix: " - Planung"
