version: 2.0-SNAPSHOT

# Spring Boot Configuration
spring:
  main:
    web-application-type: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

logging:
  level:
    ch:
      awae:
        esgcal: DEBUG

# Google API Configuration
google:
  login:
    timeout: 120
    port: 8080
    enable: true
  api:
    throttle: 5
    cache-duration: 10000

calendar:
  planning-suffix: " - Planung"

# Export Config
export:
  format: ".xlsx"
  formatESG: ".xlsm"
  fileESG: "JP.xlsm"